#!/usr/bin/env php
<?php

declare(strict_types=1);

require_once __DIR__ . '/vendor/autoload.php';

use Devbanana\LetterBoxed\Command\RemainingCommand;
use Devbanana\LetterBoxed\Validator\WordValidator;
use Symfony\Component\Console\Application;

$app = new Application('Letter Boxed Solver');
$app->add(new RemainingCommand(new WordValidator()));
$app->run();
